
export const desktopStyles = {
    "A4-2.4mm-Portrait": {
        position: "absolute",
        top: "21%",
        left: "48%",
        width: "7.5%",
        height: "10.7%",
    },
    "A4-No-Mount-Portrait": {
        position: "absolute",
        top: "19.2%",
        left: "46%",
        width: "11.5%",
        height: "14.4%",
    },
    "A3-2.4mm-Portrait": {
        position: "absolute",
        top: "18%",
        left: "45.7%",
        width: "12.2%",
        height: "16.8%",
    },
    "A3-No-Mount-Portrait": {
        position: "absolute",
        top: "16.2%",
        left: "43.6%",
        width: "16.3%",
        height: "20.4%",
    },
    "A2-2.4mm-Portrait": {
        position: "absolute",
        top: "14%",
        left: "42.9%",
        width: "17.9%",
        height: "24.4%",
    },
    "A2-No-Mount-Portrait": {
        position: "absolute",
        top: "11.8%",
        left: "40%",
        width: "23.4%",
        height: "29.1%",
    },
    "A1-2.4mm-Portrait": {
        position: "absolute",
        top: "8.3%",
        left: "38%",
        width: "27.5%",
        height: "36.3%",
    },
    "A1-No-Mount-Portrait": {
        position: "absolute",
        top: "5.8%",
        left: "35.4%",
        width: "32.9%",
        height: "41.2%",
    },
    "30x30cm-2.4mm-Square": {
        position: "absolute",
        top: "20.8%",
        left: "45.4%",
        width: "12.8%",
        height: "auto",
    },
    "30x30cm-No-Mount-Square": {
        position: "absolute",
        top: "19%",
        left: "43.4%",
        width: "17%",
        height: "auto",
    },
    "40x40cm-2.4mm-Square": {
        position: "absolute",
        top: "18%",
        left: "43%",
        width: "18%",
        height: "auto",
    },
    "40x40cm-No-Mount-Square": {
        position: "absolute",
        top: "16%",
        left: "41%",
        width: "22.2%",
        height: "auto",
    },
    "50x50cm-2.4mm-Square": {
        position: "absolute",
        top: "16.3%",
        left: "40.4%",
        width: "22.9%",
        height: "auto",
    },
    "50x50cm-No-Mount-Square": {
        position: "absolute",
        top: "14%",
        left: "37.7%",
        width: "28.2%",
        height: "auto",
    },
    "60x60cm-2.4mm-Square": {
        position: "absolute",
        top: "15%",
        left: "39%",
        width: "25.9%",
        height: "auto",
    },
    "60x60cm-No-Mount-Square": {
        position: "absolute",
        top: "11.8%",
        left: "35.3%",
        width: "33.3%",
        height: "auto",
    },
    "A4-2.4mm-Landscape": {
        position: "absolute",
        top: "23.1%",
        left: "45.7%",
        width: "12.3%",
        height: "6.8%",
    },
    "A4-No-Mount-Landscape": {
        position: "absolute",
        top: "21.2%",
        left: "43.4%",
        width: "16.6%",
        height: "10.2%",
    },
    "A3-2.4mm-Landscape": {
        position: "absolute",
        top: "21%",
        left: "42.3%",
        width: "19.1%",
        height: "10.8%",
    },
    "A3-No-Mount-Landscape": {
        position: "absolute",
        top: "19.1%",
        left: "40.1%",
        width: "23.3%",
        height: "14.5%",
    },
    "A2-2.4mm-Landscape": {
        position: "absolute",
        top: "18.6%",
        left: "38.1%",
        width: "27.4%",
        height: "15.7%",
    },
    "A2-No-Mount-Landscape": {
        position: "absolute",
        top: "18.6%",
        left: "38%",
        width: "27.4%",
        height: "15%",
    },
    "A1-2.4mm-Landscape": {
        position: "absolute",
        top: "14.3%",
        left: "31.3%",
        width: "41.1%",
        height: "24.2%",
    },
    "A1-No-Mount-Landscape": {
        position: "absolute",
        top: "11.9%",
        left: "28.5%",
        width: "46.6%",
        height: "29%",
    },
};

export const tabletStyles = {
    "A4-2.4mm-Portrait": {
        position: "absolute",
        top: "16%",
        left: "48%",
        width: "7.5%",
        height: "7.9%",
    },
    "A4-No-Mount-Portrait": {
        position: "absolute",
        top: "14.6%",
        left: "46%",
        width: "11.5%",
        height: "10.8%",
    },
    "A3-2.4mm-Portrait": {
        position: "absolute",
        top: "13.5%",
        left: "45.7%",
        width: "12.2%",
        height: "12.8%",
    },
    "A3-No-Mount-Portrait": {
        position: "absolute",
        top: "12.3%",
        left: "43.6%",
        width: "16.3%",
        height: "15.6%",
    },
    "A2-2.4mm-Portrait": {
        position: "absolute",
        top: "11%",
        left: "42.9%",
        width: "17.7%",
        height: "18.4%",
    },
    "A2-No-Mount-Portrait": {
        position: "absolute",
        top: "8.9%",
        left: "40%",
        width: "23.3%",
        height: "22.1%",
    },
    "A1-2.4mm-Portrait": {
        position: "absolute",
        top: "6.3%",
        left: "38%",
        width: "27.4%",
        height: "27.4%",
    },
    "A1-No-Mount-Portrait": {
        position: "absolute",
        top: "4.4%",
        left: "35.4%",
        width: "32.9%",
        height: "31.3%",
    },
    "30x30cm-2.4mm-Square": {
        position: "absolute",
        top: "20.8%",
        left: "45.4%",
        width: "12.8%",
        height: "auto",
    },
    "30x30cm-No-Mount-Square": {
        position: "absolute",
        top: "19%",
        left: "43.4%",
        width: "17%",
        height: "auto",
    },
    "40x40cm-2.4mm-Square": {
        position: "absolute",
        top: "18%",
        left: "43%",
        width: "18%",
        height: "auto",
    },
    "40x40cm-No-Mount-Square": {
        position: "absolute",
        top: "16%",
        left: "41%",
        width: "22.2%",
        height: "auto",
    },
    "50x50cm-2.4mm-Square": {
        position: "absolute",
        top: "16.3%",
        left: "40.4%",
        width: "22.9%",
        height: "auto",
    },
    "50x50cm-No-Mount-Square": {
        position: "absolute",
        top: "14%",
        left: "37.7%",
        width: "28.2%",
        height: "auto",
    },
    "60x60cm-2.4mm-Square": {
        position: "absolute",
        top: "15%",
        left: "39%",
        width: "25.9%",
        height: "auto",
    },
    "60x60cm-No-Mount-Square": {
        position: "absolute",
        top: "11.8%",
        left: "35.3%",
        width: "33.3%",
        height: "auto",
    },
    "A4-2.4mm-Landscape": {
        position: "absolute",
        top: "17.1%",
        left: "45.7%",
        width: "12.3%",
        height: "5.8%",
    },
    "A4-No-Mount-Landscape": {
        position: "absolute",
        top: "16.2%",
        left: "43.4%",
        width: "16.6%",
        height: "7.5%",
    },
    "A3-2.4mm-Landscape": {
        position: "absolute",
        top: "16%",
        left: "42.3%",
        width: "19.1%",
        height: "7.9%",
    },
    "A3-No-Mount-Landscape": {
        position: "absolute",
        top: "14.5%",
        left: "40.1%",
        width: "23.3%",
        height: "10.5%",
    },
    "A2-2.4mm-Landscape": {
        position: "absolute",
        top: "14%",
        left: "38.1%",
        width: "27.4%",
        height: "11.7%",
    },
    "A2-No-Mount-Landscape": {
        position: "absolute",
        top: "14.2%",
        left: "38.1%",
        width: "27.3%",
        height: "11.8%",
    },
    "A1-2.4mm-Landscape": {
        position: "absolute",
        top: "11%",
        left: "31.3%",
        width: "41.1%",
        height: "18.7%",
    },
    "A1-No-Mount-Landscape": {
        position: "absolute",
        top: "8.9%",
        left: "28.5%",
        width: "46.6%",
        height: "22%",
    },
};

export const mobileStyles = {
    "A4-2.4mm-Portrait": {
        position: "absolute",
        top: "11.5%",
        left: "48%",
        width: "7.5%",
        height: "6%",
    },
    "A4-No-Mount-Portrait": {
        position: "absolute",
        top: "10.5%",
        left: "46%",
        width: "11.5%",
        height: "8%",
    },
    "A3-2.4mm-Portrait": {
        position: "absolute",
        top: "10%",
        left: "45.7%",
        width: "12.2%",
        height: "9.2%",
    },
    "A3-No-Mount-Portrait": {
        position: "absolute",
        top: "9%",
        left: "43.6%",
        width: "16.3%",
        height: "11%",
    },
    "A2-2.4mm-Portrait": {
        position: "absolute",
        top: "8%",
        left: "42.9%",
        width: "17.9%",
        height: "13%",
    },
    "A2-No-Mount-Portrait": {
        position: "absolute",
        top: "6.5%",
        left: "40%",
        width: "23.4%",
        height: "16%",
    },
    "A1-2.4mm-Portrait": {
        position: "absolute",
        top: "8.3%",
        left: "38%",
        width: "27.5%",
        height: "20%",
    },
    "A1-No-Mount-Portrait": {
        position: "absolute",
        top: "3.2%",
        left: "35.4%",
        width: "32.9%",
        height: "22.8%",
    },
    "30x30cm-2.4mm-Square": {
        position: "absolute",
        top: "20.8%",
        left: "45.4%",
        width: "12.8%",
        height: "auto",
    },
    "30x30cm-No-Mount-Square": {
        position: "absolute",
        top: "19%",
        left: "43.4%",
        width: "17%",
        height: "auto",
    },
    "40x40cm-2.4mm-Square": {
        position: "absolute",
        top: "18%",
        left: "43%",
        width: "18%",
        height: "auto",
    },
    "40x40cm-No-Mount-Square": {
        position: "absolute",
        top: "16%",
        left: "41%",
        width: "22.2%",
        height: "auto",
    },
    "50x50cm-2.4mm-Square": {
        position: "absolute",
        top: "16.3%",
        left: "40.4%",
        width: "22.9%",
        height: "auto",
    },
    "50x50cm-No-Mount-Square": {
        position: "absolute",
        top: "14%",
        left: "37.7%",
        width: "28.2%",
        height: "auto",
    },
    "60x60cm-2.4mm-Square": {
        position: "absolute",
        top: "15%",
        left: "39%",
        width: "25.9%",
        height: "auto",
    },
    "60x60cm-No-Mount-Square": {
        position: "absolute",
        top: "11.8%",
        left: "35.3%",
        width: "33.3%",
        height: "auto",
    },
    "A4-2.4mm-Landscape": {
        position: "absolute",
        top: "17.1%",
        left: "45.7%",
        width: "12.3%",
        height: "5.8%",
    },
    "A4-No-Mount-Landscape": {
        position: "absolute",
        top: "16.2%",
        left: "43.4%",
        width: "16.6%",
        height: "7.5%",
    },
    "A3-2.4mm-Landscape": {
        position: "absolute",
        top: "16%",
        left: "42.3%",
        width: "19.1%",
        height: "7.9%",
    },
    "A3-No-Mount-Landscape": {
        position: "absolute",
        top: "14.5%",
        left: "40.1%",
        width: "23.3%",
        height: "10.5%",
    },
    "A2-2.4mm-Landscape": {
        position: "absolute",
        top: "14%",
        left: "38.1%",
        width: "27.4%",
        height: "11.7%",
    },
    "A2-No-Mount-Landscape": {
        position: "absolute",
        top: "14.2%",
        left: "38.1%",
        width: "27.3%",
        height: "11.8%",
    },
    "A1-2.4mm-Landscape": {
        position: "absolute",
        top: "11%",
        left: "31.3%",
        width: "41.1%",
        height: "18.7%",
    },
    "A1-No-Mount-Landscape": {
        position: "absolute",
        top: "8.9%",
        left: "28.5%",
        width: "46.6%",
        height: "22%",
    },
};