
export const desktopStyles = {
    "A4-2.4mm-Portrait": {
        position: "absolute",
        top: "23%",
        left: "48%",
        width: "7.5%",
        height: "13%",
    },
    "A4-No-Mount-Portrait": {
        position: "absolute",
        top: "21.5%",
        left: "46%",
        width: "11.5%",
        height: "16.4%",
    },
    "A3-2.4mm-Portrait": {
        position: "absolute",
        top: "20%",
        left: "45.7%",
        width: "12.2%",
        height: "19.2%",
    },
    "A3-No-Mount-Portrait": {
        position: "absolute",
        top: "18.2%",
        left: "43.6%",
        width: "16.3%",
        height: "23%",
    },
    "A2-2.4mm-Portrait": {
        position: "absolute",
        top: "16.3%",
        left: "42.9%",
        width: "17.7%",
        height: "27%",
    },
    "A2-No-Mount-Portrait": {
        position: "absolute",
        top: "13.5%",
        left: "40.2%",
        width: "23.1%",
        height: "32.6%",
    },
    "A1-2.4mm-Portrait": {
        position: "absolute",
        top: "9.3%",
        left: "38.3%",
        width: "27.2%",
        height: "41%",
    },
    "A1-No-Mount-Portrait": {
        position: "absolute",
        top: "6.5%",
        left: "35.4%",
        width: "32.9%",
        height: "46.6%",
    },
    "30x30cm-2.4mm-Square": {
        position: "absolute",
        top: "23.3%",
        left: "45.4%",
        width: "12.8%",
        height: "auto",
    },
    "30x30cm-No-Mount-Square": {
        position: "absolute",
        top: "21.4%",
        left: "43.4%",
        width: "16.8%",
        height: "auto",
    },
    "40x40cm-2.4mm-Square": {
        position: "absolute",
        top: "20.2%",
        left: "42.5%",
        width: "18.5%",
        height: "auto",
    },
    "40x40cm-No-Mount-Square": {
        position: "absolute",
        top: "18%",
        left: "40.4%",
        width: "23%",
        height: "auto",
    },
    "50x50cm-2.4mm-Square": {
        position: "absolute",
        top: "18.5%",
        left: "40.4%",
        width: "22.9%",
        height: "auto",
    },
    "50x50cm-No-Mount-Square": {
        position: "absolute",
        top: "15.6%",
        left: "37.7%",
        width: "28.2%",
        height: "auto",
    },
    "60x60cm-2.4mm-Square": {
        position: "absolute",
        top: "16.5%",
        left: "38.5%",
        width: "26.6%",
        height: "auto",
    },
    "60x60cm-No-Mount-Square": {
        position: "absolute",
        top: "12.9%",
        left: "35.3%",
        width: "33.4%",
        height: "auto",
    },
    "A4-2.4mm-Landscape": {
        position: "absolute",
        top: "26%",
        left: "45.7%",
        width: "12%",
        height: "7.5%",
    },
    "A4-No-Mount-Landscape": {
        position: "absolute",
        top: "24%",
        left: "43.6%",
        width: "16.2%",
        height: "11.5%",
    },
    "A3-2.4mm-Landscape": {
        position: "absolute",
        top: "23.5%",
        left: "42.3%",
        width: "19%",
        height: "12.2%",
    },
    "A3-No-Mount-Landscape": {
        position: "absolute",
        top: "21.5%",
        left: "40.1%",
        width: "23.3%",
        height: "16.5%",
    },
    "A2-2.4mm-Landscape": {
        position: "absolute",
        top: "20.7%",
        left: "38.1%",
        width: "27.4%",
        height: "17.7%",
    },
    "A2-No-Mount-Landscape": {
        position: "absolute",
        top: "20.7%",
        left: "38.1%",
        width: "27.4%",
        height: "17.7%",
    },
    "A1-2.4mm-Landscape": {
        position: "absolute",
        top: "16.3%",
        left: "31.3%",
        width: "41.1%",
        height: "26.8%",
    },
    "A1-No-Mount-Landscape": {
        position: "absolute",
        top: "13.4%",
        left: "28.5%",
        width: "46.6%",
        height: "32.7%",
    },
};

export const tabletStyles = {
    "A4-2.4mm-Portrait": {
        position: "absolute",
        top: "23%",
        left: "48%",
        width: "7.5%",
        height: "13%",
    },
    "A4-No-Mount-Portrait": {
        position: "absolute",
        top: "21.5%",
        left: "46%",
        width: "11.5%",
        height: "16.4%",
    },
    "A3-2.4mm-Portrait": {
        position: "absolute",
        top: "20%",
        left: "45.7%",
        width: "12.2%",
        height: "19.2%",
    },
    "A3-No-Mount-Portrait": {
        position: "absolute",
        top: "18.2%",
        left: "43.6%",
        width: "16.3%",
        height: "23%",
    },
    "A2-2.4mm-Portrait": {
        position: "absolute",
        top: "16.3%",
        left: "42.9%",
        width: "17.7%",
        height: "27%",
    },
    "A2-No-Mount-Portrait": {
        position: "absolute",
        top: "13.5%",
        left: "40.2%",
        width: "23.1%",
        height: "32.6%",
    },
    "A1-2.4mm-Portrait": {
        position: "absolute",
        top: "9.3%",
        left: "38.3%",
        width: "27.2%",
        height: "41%",
    },
    "A1-No-Mount-Portrait": {
        position: "absolute",
        top: "6.5%",
        left: "35.4%",
        width: "32.9%",
        height: "46.6%",
    },
    "30x30cm-2.4mm-Square": {
        position: "absolute",
        top: "23.3%",
        left: "45.4%",
        width: "12.8%",
        height: "auto",
    },
    "30x30cm-No-Mount-Square": {
        position: "absolute",
        top: "21.4%",
        left: "43.4%",
        width: "16.8%",
        height: "auto",
    },
    "40x40cm-2.4mm-Square": {
        position: "absolute",
        top: "20.2%",
        left: "42.5%",
        width: "18.5%",
        height: "auto",
    },
    "40x40cm-No-Mount-Square": {
        position: "absolute",
        top: "18%",
        left: "40.4%",
        width: "23%",
        height: "auto",
    },
    "50x50cm-2.4mm-Square": {
        position: "absolute",
        top: "18.5%",
        left: "40.4%",
        width: "22.9%",
        height: "auto",
    },
    "50x50cm-No-Mount-Square": {
        position: "absolute",
        top: "15.6%",
        left: "37.7%",
        width: "28.2%",
        height: "auto",
    },
    "60x60cm-2.4mm-Square": {
        position: "absolute",
        top: "16.5%",
        left: "38.5%",
        width: "26.6%",
        height: "auto",
    },
    "60x60cm-No-Mount-Square": {
        position: "absolute",
        top: "12.9%",
        left: "35.3%",
        width: "33.4%",
        height: "auto",
    },
    "A4-2.4mm-Landscape": {
        position: "absolute",
        top: "17.1%",
        left: "45.7%",
        width: "12.3%",
        height: "5.8%",
    },
    "A4-2.4mm-Landscape": {
        position: "absolute",
        top: "26%",
        left: "45.7%",
        width: "12%",
        height: "7.5%",
    },
    "A4-No-Mount-Landscape": {
        position: "absolute",
        top: "24%",
        left: "43.6%",
        width: "16.2%",
        height: "11.5%",
    },
    "A3-2.4mm-Landscape": {
        position: "absolute",
        top: "23.5%",
        left: "42.3%",
        width: "19%",
        height: "12.2%",
    },
    "A3-No-Mount-Landscape": {
        position: "absolute",
        top: "21.5%",
        left: "40.1%",
        width: "23.3%",
        height: "16.5%",
    },
    "A2-2.4mm-Landscape": {
        position: "absolute",
        top: "20.7%",
        left: "38.1%",
        width: "27.4%",
        height: "17.7%",
    },
    "A2-No-Mount-Landscape": {
        position: "absolute",
        top: "20.7%",
        left: "38.1%",
        width: "27.4%",
        height: "17.7%",
    },
    "A1-2.4mm-Landscape": {
        position: "absolute",
        top: "16.3%",
        left: "31.3%",
        width: "41.1%",
        height: "26.8%",
    },
    "A1-No-Mount-Landscape": {
        position: "absolute",
        top: "13.4%",
        left: "28.5%",
        width: "46.6%",
        height: "32.7%",
    },
};

export const mobileStyles = {
    "A4-2.4mm-Portrait": {
        position: "absolute",
        top: "13%",
        left: "48%",
        width: "7.5%",
        height: "7%",
    },
    "A4-No-Mount-Portrait": {
        position: "absolute",
        top: "11.8%",
        left: "46%",
        width: "11.5%",
        height: "9%",
    },
    "A3-2.4mm-Portrait": {
        position: "absolute",
        top: "11%",
        left: "45.7%",
        width: "12.2%",
        height: "10.5%",
    },
    "A3-No-Mount-Portrait": {
        position: "absolute",
        top: "10%",
        left: "43.6%",
        width: "16.5%",
        height: "13%",
    },
    "A2-2.4mm-Portrait": {
        position: "absolute",
        top: "8.8%",
        left: "42.9%",
        width: "17.5%",
        height: "15%",
    },
    "A2-No-Mount-Portrait": {
        position: "absolute",
        top: "7.4%",
        left: "40%",
        width: "23.4%",
        height: "18%",
    },
    "A1-2.4mm-Portrait": {
        position: "absolute",
        top: "8.3%",
        left: "38%",
        width: "27.5%",
        height: "20%",
    },
    "A1-No-Mount-Portrait": {
        position: "absolute",
        top: "3.5%",
        left: "35.4%",
        width: "32.9%",
        height: "25.8%",
    },
    "30x30cm-2.4mm-Square": {
        position: "absolute",
        top: "12.8%",
        left: "45.4%",
        width: "12.8%",
        height: "auto",
    },
    "30x30cm-No-Mount-Square": {
        position: "absolute",
        top: "11.6%",
        left: "43.4%",
        width: "17%",
        height: "auto",
    },
    "40x40cm-2.4mm-Square": {
        position: "absolute",
        top: "11.1%",
        left: "42.2%",
        width: "18.7%",
        height: "auto",
    },
    "40x40cm-No-Mount-Square": {
        position: "absolute",
        top: "9.9%",
        left: "40.4%",
        width: "22.8%",
        height: "auto",
    },
    "50x50cm-2.4mm-Square": {
        position: "absolute",
        top: "10.1%",
        left: "40.4%",
        width: "22.9%",
        height: "auto",
    },
    "50x50cm-No-Mount-Square": {
        position: "absolute",
        top: "8.5%",
        left: "37.7%",
        width: "28.2%",
        height: "auto",
    },
    "60x60cm-2.4mm-Square": {
        position: "absolute",
        top: "9.1%",
        left: "38.5%",
        width: "26.6%",
        height: "auto",
    },
    "60x60cm-No-Mount-Square": {
        position: "absolute",
        top: "7.2%",
        left: "35.4%",
        width: "33.3%",
        height: "auto",
    },
    "A4-2.4mm-Landscape": {
        position: "absolute",
        top: "14.3%",
        left: "45.7%",
        width: "12.3%",
        height: "4%",
    },
    "A4-No-Mount-Landscape": {
        position: "absolute",
        top: "13.2%",
        left: "43.4%",
        width: "16.6%",
        height: "6.5%",
    },
    "A3-2.4mm-Landscape": {
        position: "absolute",
        top: "13%",
        left: "42.3%",
        width: "19.1%",
        height: "6.9%",
    },
    "A3-No-Mount-Landscape": {
        position: "absolute",
        top: "11.8%",
        left: "40.1%",
        width: "23.3%",
        height: "9.2%",
    },
    "A2-2.4mm-Landscape": {
        position: "absolute",
        top: "11.6%",
        left: "38.1%",
        width: "27.4%",
        height: "9.7%",
    },
    "A2-No-Mount-Landscape": {
        position: "absolute",
        top: "11.6%",
        left: "38.1%",
        width: "27.4%",
        height: "9.7%",
    },
    "A1-2.4mm-Landscape": {
        position: "absolute",
        top: "9%",
        left: "31.3%",
        width: "41.1%",
        height: "14.7%",
    },
    "A1-No-Mount-Landscape": {
        position: "absolute",
        top: "7.5%",
        left: "28.5%",
        width: "46.6%",
        height: "18%",
    },
};